# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

################################################################################################################################################
# Fortify lets you build secure software fast with an appsec platform that automates testing throughout the DevSecOps pipeline. Fortify static,#
# dynamic, interactive, and runtime security testing is available on premises or as a service. To learn more about Fortify, start a free trial #
# or contact our sales team, visit microfocus.com/appsecurity.                                                                                 #
#                                                                                                                                              #
# Use this workflow template as a basis for integrating Fortify on Demand Static Application Security Testing(SAST) into your GitHub workflows.#
# This template demonstrates the steps to prepare the code+dependencies, initiate a scan, download results once complete and import into       #
# GitHub Security Code Scanning Alerts. Existing customers should review inputs and environment variables below to configure scanning against  #
# an existing application in your Fortify on Demand tenant. Additional information is available in the comments throughout the workflow, the   #
# documentation for the Fortify actions used, and the Fortify on Demand / ScanCentral Client product documentation. If you need additional     #
# assistance with configuration, feel free to create a help ticket in the Fortify on Demand portal.                                            #
################################################################################################################################################

name: Fortify on Demand Scan

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  FoD-SAST-Scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v3
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      # Java is required to run the various Fortify utilities.
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      # Identify open source components for Debricked scan
      - uses: debricked/actions/cache@v3
      - uses: debricked/actions/resolve-non-docker@v3

      - name: Archive Debricked lock file
        uses: actions/upload-artifact@v3
        with:
          name: debricked-lock-file
          path: '*.debricked.lock'

      - name: Check Files #1
        run: ls -la
      
      # Prepare source+dependencies for upload. 
      - name: Download Fortify ScanCentral Client
        uses: fortify/gha-setup-scancentral-client@v2
      - name: Package Code + Dependencies
        #run: scancentral package -oss -pyr requirements.txt -o package.zip
        run: scancentral package -o package.zip

      - name: Check Files #2
        run: ls -la

      - name: Archive ScanCentral package
        uses: actions/upload-artifact@v3
        with:
          name: scancentral-package
          path: package.zip
          retention-days: 1
