name: Debricked Resolve Test

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  Debricked-Resolve:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v3
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      # Java is required to run the various Fortify utilities.
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      # Identify open source components for Debricked scan
      - uses: debricked/actions/cache@v3
      - uses: debricked/actions/resolve-non-docker@v3
      
      - name: Find Debricked Lock File
        run: find . -name *.debricked.lock
      
      - name: Archive Debricked lock file
        uses: actions/upload-artifact@v3
        with:
          name: debricked-lock-file
          path: '*.debricked.lock'

